IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='AdditionalInfo' AND xtype='U')
CREATE TABLE AdditionalInfo (
    Id BIGINT PRIMARY KEY IDENTITY(1,1),
    UId UNIQUEIDENTIFIER NOT NULL,
    ServicesAvailable BIT NOT NULL,
    SitterRequired BIT NOT NULL,
    VTIBDrips BIT NOT NULL,
    Dialysis BIT NOT NULL,
    PFCTTransfer BIT NOT NULL,
    CovidWithin3Days BIT NOT NULL,
    FaceSheet SMALLINT NOT NULL,
    HAndP SMALLINT NOT NULL,
    CovidTestResults SMALLINT NOT NULL,
    TransferOrder SMALLINT NOT NULL,
    ProgressNotes SMALLINT NOT NULL,
    ConsultationNotes SMALLINT NOT NULL,
    MostRecentLabResults SMALLINT NOT NULL,
    RadiologyResults SMALLINT NOT NULL,
    MedicationList SMALLINT NOT NULL,
    TreatmentsAndProceduresInED SMALLINT NOT NULL,
    InsuranceAuthorization SMALLINT NOT NULL,
    OtherNotes VARCHAR(200) NULL,
    CodeStatus VARCHAR(200) NULL,
    LifeImageUploadRequested SMALLINT NOT NULL,
    SendingFacilityUnableToUseLifeImage SMALLINT NOT NULL,
    ColdOrFluSymptoms BIT NOT NULL,
    NewRashUnknownCause BIT NOT NULL,
    ContactWithCovidPositive BIT NOT NULL,
    DiagnosedCovidOrPositiveLab BIT NOT NULL,
    CovidDiagnosisDates DATETIME NULL,
    SickHouseholdMembers BIT NOT NULL,
    ExposedToMeasles BIT NOT NULL,
    TraveledOutsideUS BIT NOT NULL,
    TraveledArabianPeninsula BIT NOT NULL,
    TraveledAfrica BIT NOT NULL,
    HasRespiratoryIllnessAfterTravel BIT NOT NULL,
    AdmittedToKindredHospital BIT NOT NULL,
    MultiDrugResistantInfection BIT NOT NULL,
    Microorganisms VARCHAR(200) NULL,
    CommunicableDisease BIT NOT NULL,
    DiseaseConditions VARCHAR(200) NULL,
    LabResultsStatus SMALLINT NOT NULL,
    DiagnosticsStatus SMALLINT NOT NULL,
    MedicationListStatus SMALLINT NOT NULL
);