IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ComorbiditiesAndRiskScore' AND xtype='U')
CREATE TABLE ComorbiditiesAndRiskScore (
    Id BIGINT PRIMARY KEY,
    None BIT NOT NULL,
    StrokeTIA BIT NOT NULL,
    CHF BIT NOT NULL,
    CKD_ESRD BIT NOT NULL,
    HTN BIT NOT NULL,
    DiabetesOrSkinIssues BIT NOT NULL,
    MI_Angina_CAD BIT NOT NULL,
    COPDOrRespiratoryFailure BIT NOT NULL,
    Ventilated BIT NOT NULL,
    PulmonaryHTN BIT NOT NULL,
    PulmonaryHTN_Prostacyclin BIT NOT NULL,
    ImmunocompromisedOrHIV BIT NOT NULL,
    PsychBackground BIT NOT NULL,
    NonCompliantWithCare BIT NOT NULL,
    UnableToPerformADLs BIT NOT NULL,
    DrugOrAlcoholDependence BIT NOT NULL,
    LymphomaLeukemiaCancer BIT NOT NULL,
    MalnutritionObesityDigestiveDisease BIT NOT NULL,
    UnconsciousOrALOC BIT NOT NULL,
    LOSMoreThan2Weeks BIT NOT NULL,
    OutOfServiceArea BIT NOT NULL,
    DNRCodeStatus BIT NOT NULL,
    CovidPositive BIT NOT NULL,
    RecentSurgeryAtUCI BIT NOT NULL,
    RecentSurgeryOutsideUCI BIT NOT NULL,
    TotalPoints INT NULL
);