// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransferCenterDbStore.Data;

#nullable disable

namespace TransferCenterDbStore.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20251028190438_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransferCenterDbStore.Entities.AdditionalInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AdmittedToKindredHospital")
                        .HasColumnType("bit");

                    b.Property<string>("CodeStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ColdOrFluSymptoms")
                        .HasColumnType("bit");

                    b.Property<bool>("CommunicableDisease")
                        .HasColumnType("bit");

                    b.Property<short>("ConsultationNotes")
                        .HasColumnType("smallint");

                    b.Property<bool>("ContactWithCovidPositive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CovidDiagnosisDates")
                        .HasColumnType("datetime2");

                    b.Property<short>("CovidTestResults")
                        .HasColumnType("smallint");

                    b.Property<bool>("CovidWithin3Days")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DiagnosedCovidOrPositiveLab")
                        .HasColumnType("bit");

                    b.Property<short>("DiagnosticsStatus")
                        .HasColumnType("smallint");

                    b.Property<bool>("Dialysis")
                        .HasColumnType("bit");

                    b.Property<string>("DiseaseConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExposedToMeasles")
                        .HasColumnType("bit");

                    b.Property<short>("FaceSheet")
                        .HasColumnType("smallint");

                    b.Property<short>("HAndP")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasRespiratoryIllnessAfterTravel")
                        .HasColumnType("bit");

                    b.Property<short>("InsuranceAuthorization")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<short>("LabResultsStatus")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<short>("LifeImageUploadRequested")
                        .HasColumnType("smallint");

                    b.Property<short>("MedicationList")
                        .HasColumnType("smallint");

                    b.Property<short>("MedicationListStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("Microorganisms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("MostRecentLabResults")
                        .HasColumnType("smallint");

                    b.Property<bool>("MultiDrugResistantInfection")
                        .HasColumnType("bit");

                    b.Property<bool>("NewRashUnknownCause")
                        .HasColumnType("bit");

                    b.Property<string>("OtherNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PFCTTransfer")
                        .HasColumnType("bit");

                    b.Property<short>("ProgressNotes")
                        .HasColumnType("smallint");

                    b.Property<short>("RadiologyResults")
                        .HasColumnType("smallint");

                    b.Property<short>("SendingFacilityUnableToUseLifeImage")
                        .HasColumnType("smallint");

                    b.Property<bool>("ServicesAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("SickHouseholdMembers")
                        .HasColumnType("bit");

                    b.Property<bool>("SitterRequired")
                        .HasColumnType("bit");

                    b.Property<short>("TransferOrder")
                        .HasColumnType("smallint");

                    b.Property<short>("TransferType")
                        .HasColumnType("smallint");

                    b.Property<bool>("TraveledAfrica")
                        .HasColumnType("bit");

                    b.Property<bool>("TraveledArabianPeninsula")
                        .HasColumnType("bit");

                    b.Property<bool>("TraveledOutsideUS")
                        .HasColumnType("bit");

                    b.Property<short>("TreatmentsAndProceduresInED")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("VTIBDrips")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AdditionalInfo");
                });

            modelBuilder.Entity("TransferCenterDbStore.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("TransferCenterDbStore.Entities.ComorbiditiesAndRiskScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CHF")
                        .HasColumnType("bit");

                    b.Property<bool>("CKD_ESRD")
                        .HasColumnType("bit");

                    b.Property<bool>("COPDOrRespiratoryFailure")
                        .HasColumnType("bit");

                    b.Property<string>("Comorbidities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CovidPositive")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DNRCodeStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("DiabetesOrSkinIssues")
                        .HasColumnType("bit");

                    b.Property<bool>("DrugOrAlcoholDependence")
                        .HasColumnType("bit");

                    b.Property<bool>("HTN")
                        .HasColumnType("bit");

                    b.Property<bool>("ImmunocompromisedOrHIV")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LOSMoreThan2Weeks")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LymphomaLeukemiaCancer")
                        .HasColumnType("bit");

                    b.Property<bool>("MI_Angina_CAD")
                        .HasColumnType("bit");

                    b.Property<bool>("MalnutritionObesityDigestiveDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("NonCompliantWithCare")
                        .HasColumnType("bit");

                    b.Property<bool>("None")
                        .HasColumnType("bit");

                    b.Property<bool>("OutOfServiceArea")
                        .HasColumnType("bit");

                    b.Property<bool>("PsychBackground")
                        .HasColumnType("bit");

                    b.Property<bool>("PulmonaryHTN")
                        .HasColumnType("bit");

                    b.Property<bool>("PulmonaryHTN_Prostacyclin")
                        .HasColumnType("bit");

                    b.Property<bool>("RecentSurgeryAtUCI")
                        .HasColumnType("bit");

                    b.Property<bool>("RecentSurgeryOutsideUCI")
                        .HasColumnType("bit");

                    b.Property<double>("RiskScore")
                        .HasColumnType("float");

                    b.Property<bool>("StrokeTIA")
                        .HasColumnType("bit");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<bool>("UnableToPerformADLs")
                        .HasColumnType("bit");

                    b.Property<bool>("UnconsciousOrALOC")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ventilated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ComorbiditiesAndRiskScores");
                });

            modelBuilder.Entity("TransferCenterDbStore.Entities.PatientDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AcceptingPhysician")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Capitated")
                        .HasColumnType("bit");

                    b.Property<string>("CodeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GCS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Gender")
                        .HasColumnType("smallint");

                    b.Property<bool>("HLOC")
                        .HasColumnType("bit");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIsolation")
                        .HasColumnType("bit");

                    b.Property<string>("IsolationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JehovahWitness")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lateral")
                        .HasColumnType("bit");

                    b.Property<string>("LevelOfCareNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientInsurance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForTransfer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sitter")
                        .HasColumnType("bit");

                    b.Property<short>("TransferType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<short>("WeightIn")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("PatientDetails");
                });

            modelBuilder.Entity("TransferCenterDbStore.Entities.PatientTransferInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AdmitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaseMgrSwRn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHloc")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MR")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryCallerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferringMd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferringMdPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferringSpecialist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferringSpecialistPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestingFacility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondFaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryCallerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("TransferType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PatientTransferInfo");
                });

            modelBuilder.Entity("TransferCenterDbStore.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DomainID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Role")
                        .HasColumnType("smallint");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.ToTable(tb => tb.ExcludeFromMigrations());
                });
#pragma warning restore 612, 618
        }
    }
}
